feature: chat gateways component main table created [WTEL-1992]
webitel/client pull request #185
Opened 2021-08-16 12:43 UTC by Vasjamel

2021-08-16 20:30 UTC, dlohvinov requested changes
в цілому, гарна робота :)
Якщо все гарно відображається і працює, то все взагалі круто
більшість речей, які я комментував - стилістичні, або кращі з точки зору досвіду/логіки, проте не є критичними, а значить, що працювало би воно і без цього)

доречі, щодо стилістики: якщо ти часто пропускаєш `;`, пусті рядки чи щось таке -- спробуй запускати перед коммітом `npm run lint` (чи якось так) -- він тобі автоматично ось такі стилістичні штуки повиправляє і ні тобі ні мені не буде потреби то вичитувати і бігати шукати фіксати

2021-08-16 20:30 UTC, dlohvinov commented on src/app/locale/en/en.js
> +        chatGateways: 'Chat gateway | Chat gateways',
мені здається тут проситься єнама з адмінки, і локаль назви розділу звідти ж взяти -- але я не пам'ятаю, як саме там то написано і чи добре воно зайде -- завтра гляну

2021-08-16 20:30 UTC, dlohvinov commented on src/app/router/router.js
> +const chatGateways = () => import('../../modules/routing/modules/chat-gateways/components/the-chat-gateways');
краще `PascalCase`, тобто, перша буква теж велика
старіші компоненти `camelCase`'ом написані, бо це було давно і я тоді цю стилістичну штуку завтикав :(

2021-08-16 20:30 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/the-chat-gateways.vue
> +  <wt-page-wrapper :actions-panel="false" class="gateways">
`class=gateways`

2021-08-16 20:30 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/the-chat-gateways.vue
> +            sortable
сортування працює, та?

2021-08-16 20:30 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/the-chat-gateways.vue
> +              {{ item.flow.name }}
я у таких випадках завжди обгортаю у `div` і роблю перевірку на `v-if=flow`
але, насправді, круто було б потестити, що буде якщо не обгортати - і чи справді у цій обгортці є сенс?

2021-08-16 20:30 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/the-chat-gateways.vue
> +
зайвий рядок :)

2021-08-16 20:30 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/the-chat-gateways.vue
> +              <wt-icon icon-prefix="messenger" :icon="iconType(item)" sm></wt-icon>
`iconType` - попроси будь-ласка у Романа подивитись і оцінити це рішення)
без жартів, я йому колись розповідав про цю штуку)

2021-08-16 20:30 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/the-chat-gateways.vue
> +
зайвий рядок :)

2021-08-16 20:30 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/the-chat-gateways.vue
> +  name: 'the-chat-gateways',
спершу нейм краще - бо так всюди)

2021-08-16 20:30 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/the-chat-gateways.vue
> +
:)

2021-08-16 20:30 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/store/chatGateways.js
> +import ChatGatewaysAPI from '../api/chatGateways'
пропущена `;` :)

2021-08-16 20:30 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/store/chatGateways.js
> +const mutations = {}
`;`

2021-08-16 20:30 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/store/internals/headers.js
> +    field: 'onOff',
`field` - то бекенд філд, по якому, наприклад, сортування або вибір колонок які показувати відбувається
стейт на бекенді справді називається `onOff`?

2021-08-16 20:30 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/store/internals/headers.js
> +    locale: 'objects.lookups.media.provider',
а ось тут уважно: слово провайдер, може-то вже і є, але у медіа провайдер і тут провайдер мають зовсім різне значення, тому тут треба створити окрему локаль, адже, наприклад, тут може захотітись змінити слово "провайдер" на слово "месседжер" - але для медіа це буде неактуально :)

2021-08-16 20:30 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/store/internals/headers.js
> +    locale: 'Url',
все одно краще локаль вносити, і просто на всі 3 мови продублювати те саме

2021-08-16 20:30 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/store/internals/headers.js
> +    locale: 'objects.routing.flow.flow',
там, здається, plural form: `'flow | flows'` - і тут просто повезло, що 1ша локаль, яка йде по дефолту - є саме тою, що тут потрібна)
щоб обійти везіння і забезпечити результат, краще визначати plural locale (саме тут) як `locale: ['path', 1]`

2021-08-16 20:30 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/store/internals/headers.js
> +    field: 'r_state',
у профайдера філд `r_state`?)

2021-08-16 20:32 UTC, dlohvinov commented
і, пінгани мене завтра, треба ще у `scope`  пермішенах захендлити цей розділ

2021-08-17 09:53 UTC, Vasjamel commented on src/app/router/router.js
> +const chatGateways = () => import('../../modules/routing/modules/chat-gateways/components/the-chat-gateways');
done

2021-08-28 14:04 UTC, dlohvinov commented
треба розбити на менші

2021-08-28 14:04 UTC, closed without merging