feature: added ui button customization [WTEL-1992]
webitel/client pull request #199
Opened 2021-09-06 11:18 UTC by Vasjamel

2021-09-06 11:34 UTC, dlohvinov commented on src/app/locale/ru/ru.js
> +          btnOpacity: 'Прозрачность',
`Прозначность кнопки` би

2021-09-06 11:34 UTC, dlohvinov commented on src/app/locale/ua/ua.js
> +          btnOpacity: 'Прозорість',
same

2021-09-06 11:34 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-general-tab.vue
> +      <div class="pes">
м?

2021-09-06 11:34 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +    height: 4rem;
`px` би -- буде дивно якщо нічого не мінятиметься від фонт-сайзу клієнта, крім цього кругляшка))

2021-09-06 11:34 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +  // },
най це буде у дефолт конфігу. просто не треба це на юі виводити

2021-09-06 11:34 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +  + 'document.head.appendChild(link);';
треба красивіше)

2021-09-06 11:34 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +    }),
маппери краще перед самими метоадми

2021-09-06 11:34 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +    },
добре

2021-09-06 11:34 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +      }
це можна (і навіть нужна) зробити без циклу

2021-09-06 11:34 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +      }
і взагалі ось ці форматування було би круто винести у якийс ьметод типу `normalizeConfig` (якщо за межами `export default`), або `getNormalizedConfig` -- якщо у `methods` щоб рознести трохи логіку по різних шматках

2021-09-06 11:34 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +        return dispatch(`${this.namespace}/SET_WEBCHAT_VIEW`, payload);
але ж ти тут сетаєш не вебчатВью, а вебчатВью проперті?

2021-09-06 11:34 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +      ></wt-select>
я на цих селектах не бачу пропса який не дає підчищати інпут до пустого велью, хоча ніби пам'ятаю що ти це робив і у тебе ті хрестики з видаленням не малюватись?

2021-09-07 15:23 UTC, dlohvinov requested changes

2021-09-07 15:23 UTC, dlohvinov commented on src/app/locale/ru/ru.js
> +          left: 'Левая',
може би краще "Слева" "Справа"?
(укр аналоігчно)

2021-09-07 15:23 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-general-tab.vue
> +        @input="setItemProp({ prop: 'name', value: $event})"
м?)

2021-09-07 15:23 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +        @input="setWebchatViewProperty({prop: 'lang', value: $event.value})"
` ` after `event.value`

2021-09-07 15:23 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +        @input="setWebchatViewProperty({prop: 'borderRadiusStyle', value: $event.value})"
` ` after `event.value`

2021-09-07 15:23 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +          <div class="color-template" :style="getHsl"></div>
`get...` предполагает, що там якась функція чи щось таке, як правило
чому б не назвати це якось типу `hslPreview` чи `hslPreviewStyle`?

2021-09-07 15:23 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +        @input="setWebchatViewProperty({prop: 'btnOpacity',value: $event})"
` ` after `event.value`

2021-09-07 15:23 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +      }
викликати якийсь сеттер на компьютері -- якась дуууже погана іедя через неявність цього виклику
потім здуріти можна буде знайти де та проперті сетається, якщо пошуком не користатись

2021-09-07 15:58 UTC, Vasjamel commented on src/app/locale/ru/ru.js
> +          left: 'Левая',
done

2021-09-07 15:58 UTC, Vasjamel commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-general-tab.vue
> +        @input="setItemProp({ prop: 'name', value: $event})"
done

2021-09-07 15:58 UTC, Vasjamel commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +        @input="setWebchatViewProperty({prop: 'lang', value: $event.value})"
done

2021-09-07 15:58 UTC, Vasjamel commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +        @input="setWebchatViewProperty({prop: 'borderRadiusStyle', value: $event.value})"
done

2021-09-07 15:58 UTC, Vasjamel commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +        @input="setWebchatViewProperty({prop: 'btnOpacity',value: $event})"
done

2021-09-08 09:30 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +        @input="setWebchatViewProperty({prop: 'btnOpacity',value: $event })"
` ` before `prop`

2021-09-08 09:30 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +        @input="setWebchatViewProperty({prop: 'borderRadiusStyle', value: $event.value })"
` ` before `prop`

2021-09-08 09:30 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +        @input="setWebchatViewProperty({prop: 'lang', value: $event.value })"
` ` before `prop`

2021-09-08 09:30 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +    generateCode({ btnOpacity, accentColor, borderRadiusStyle, lang, logoUrl, position }) {
а для чого метод у методах, якщо він не використовує `this`?

2021-09-08 09:30 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +    },
а для чого метод у методах, якщо він не використовує `this`?

2021-09-08 09:30 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +      const accentColor = this.hslColor;
`const` -> obj.reassign

2021-09-08 09:37 UTC, dlohvinov requested changes

2021-09-08 09:37 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +      script.src = 'https://cloud.webitel.ua/omni-widget/WtOmniWidget.umd.js';
base url

2021-09-08 09:37 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +      link.href = 'https://cloud.webitel.ua/omni-widget/WtOmniWidget.css';
base url

2021-09-08 10:08 UTC, dlohvinov requested changes

2021-09-08 10:08 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
>      },
return config

2021-09-08 10:22 UTC, dlohvinov requested changes

2021-09-08 10:22 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +  wsUrl: '',
`/ws`

2021-09-08 10:22 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +  return Object.keys(defaultConfig).reduce((config, key) => ({
можна обійтись без `return`

2021-09-08 10:22 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +      this.setWebchatViewProperty({ prop: 'accentColor', value: value });
`value: value` -> `value`

2021-09-08 10:22 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +      },
rm

2021-09-10 10:14 UTC, dlohvinov approved these changes

2021-09-10 10:14 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +      { name: 'Ukrainian', value: 'ua' },
locales

2021-09-10 10:14 UTC, merged