feature: added colorpicker and opacity slider [WTEL-1992]
webitel/client pull request #200
Opened 2021-09-10 13:45 UTC by Vasjamel

2021-09-10 14:36 UTC, dlohvinov requested changes

2021-09-10 14:36 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +        @input="setWebchatViewProperty({prop: 'lang', value: $event.value})"
.

2021-09-10 14:36 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +            <wt-label>Button opacity</wt-label>
`labels` -> locale

2021-09-10 14:36 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +      return this.isCopied ? this.$t('objects.copied') : this.$t('objects.copy').concat(' code for site');
locale

2021-09-10 14:36 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +  vertical-align: middle;
хіба це не робить `align-items`?

2021-09-10 14:36 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +  .wt-label{
` `

2021-09-10 14:36 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> -            :label="$t('objects.routing.chatGateways.metadata.saturation')"
не підчистив локалі

2021-09-10 14:36 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> -            :value="itemInstance.metadata.view.lightness"
підчистити вью.лайтнес... з ітемІнстанс схеми

2021-09-10 14:45 UTC, Vasjamel commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +        @input="setWebchatViewProperty({prop: 'lang', value: $event.value})"
+

2021-09-10 14:45 UTC, Vasjamel commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +        @input="setWebchatViewProperty({prop: 'lang', value: $event.value})"
done

2021-09-10 14:45 UTC, Vasjamel commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +            <wt-label>Button opacity</wt-label>
done

2021-09-10 14:51 UTC, Vasjamel commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +      return this.isCopied ? this.$t('objects.copied') : this.$t('objects.copy').concat(' code for site');
done

2021-09-10 14:52 UTC, Vasjamel commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +  vertical-align: middle;
done

2021-09-10 14:52 UTC, Vasjamel commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +  .wt-label{
done

2021-09-10 14:52 UTC, Vasjamel commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> -            :label="$t('objects.routing.chatGateways.metadata.saturation')"
done

2021-09-10 14:56 UTC, Vasjamel commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> -            :value="itemInstance.metadata.view.lightness"
done

2021-09-10 15:34 UTC, dlohvinov reviewed
продивись будь ласка все ще раз на предмет пропущених чи провтиканих штук

2021-09-14 07:40 UTC, dlohvinov reviewed
прохання: якщо ти щось заміняєш/видаляєш, не забувай підчистити попередній спосіб, як ти це робив, тому що коли ти цього не робиш а я це бачу і пишу тобі (як з видаленням екшенів зі стора), це кожного разу понижує довіру і спокій що я просто можу глянути останній комміт і знати що Вася все підчистив і все круто і я маю дивитись тільки на суть, а не на стилістику, пропущені пробіли і не видалені методи. 

На противагу, така ситуація значно ускладнює мені процес рев'ю, бо я змушений купу всього що Вася написав постійно тримати в голові, щоб якщо Вася щось забуде, щоб це не забув і випадково не аппрувнув я, і потім не довелось розбиратись що то воно, нашо, і підчищати через пів року, коли доведеться до того вертатись.

 Через це рев'ю проходять довше, мені значно менше хочеться їх проводити, адже я витрачаю більше ментального ресурсу, і закрадається відчуття, що мені треба кожен твій крок контролювати і дивитись за такими речами, щоб все було добре.

2021-09-14 07:40 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +}
а чи справді там десь його копія тоді потрібна?)

2021-09-14 07:40 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> -      setWebchatViewProperty(dispatch, payload) {
здається, ти екшен не видалив цей зі стора

2021-09-14 07:40 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +      },
а що буде якщо просто тупо забрати звідси ргба?

2021-09-14 07:40 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +      const l = +this.color.hsl.l <= 1 ? +this.color.hsl.l.toFixed(2) * 100 : +this.color.hsl.l.toFixed(2);
тобто, чи правильно я розумію: його значення може бути і менше 1, і 1-100?

2021-09-14 07:40 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +        .filter((language) => language.value === this.itemInstance.metadata.lang);
питання: чому тут замість `filter` краще взяти `find`?

2021-09-14 07:40 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +  mounted() {
я би це робив на `created()`, бо до юайки ці маніпуляції відношення не мають, а отже чому чекати доки вона намалюється, щоб потім чекати доки це виконається, замість зробити це паралельно?

2021-09-14 07:40 UTC, dlohvinov commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +      };
я би кожен цей `restore${Value}` виніс би в окремий метод, і тут їх викликав -- просто з точки зору охайності

2021-09-14 07:43 UTC, dlohvinov commented
якщо тобі треба більше часу на то щоб все передивитись і підчистити -- то бери його без проблем
або якщо тобі на свіжу голову це простіше -- то спокійно бери собі час до ранку і, передивляйся і комміть все тільки коли приходиш -- у гіршому випадку це все одно займає і час і мороку -- але так вони принаймні будуть передбачувані, виправдані і без негативу)

2021-09-14 11:17 UTC, Vasjamel commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +      },
тоді не буде нормально видно слайдера з опасіті, бо він якраз під rgba підв'язаний.

2021-09-14 11:20 UTC, Vasjamel commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +      const l = +this.color.hsl.l <= 1 ? +this.color.hsl.l.toFixed(2) * 100 : +this.color.hsl.l.toFixed(2);
так, все правильно: 
1. Від 0 до 1 значення, яке приходить нам з колорпікера, ми його мусимо перевести у відсоток від 1 до 100, щоб передати конфіг з форматом hsl
2. У відсотках (від 1 до 100)  до нас значення приходить в форматі hsl, тому тут так.

2021-09-14 11:22 UTC, Vasjamel commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +        .filter((language) => language.value === this.itemInstance.metadata.lang);
бо фільтр нам повертає масив елементів, які пройшли, 
а тут ми точно знаємо, що в нас завжди буде тільки один елемент. Тому тут досить валідне зауваження, зараз переробляю

2021-09-14 12:03 UTC, Vasjamel commented on src/modules/routing/modules/chat-gateways/components/opened-chat-gateway-webchat-view-tab.vue
> +}
deleted

2021-09-14 12:39 UTC, dlohvinov approved these changes

2021-09-14 13:35 UTC, merged