fix: queues and permissions
webitel/client pull request #61
Opened 2020-11-19 13:31 UTC by VoroniakPavlo

2020-11-19 14:13 UTC, dlohvinov requested changes

2020-11-19 14:13 UTC, dlohvinov commented on src/store/modules/permissions/objects/objects.js
> +            context.dispatch('SEARCH_DEFAULT_LIST');
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/try...catch
розділ про finally

2020-11-19 14:13 UTC, dlohvinov commented on src/store/modules/permissions/objects/objects.js
> +        if(ruleName == 'd') { have = rule.perm.d;}
якщо я правильно розумію це, проситься if-else
шарю, що то я писав, тому тут правило бойскаута працює))
`Любой код рано или поздно загнивает. Чтобы этого не происходило следует соблюдать «правило бойскаута»: «оставь место стоянки чище, чем оно было до твоего прихода». Чистка не обязательно должна быть глобальной, достаточно почистить хотя бы небольшой кусок кода, режущий глаз.`

лінк: http://developer.uz/books/chistiy_cod#:~:text=%D0%9B%D1%8E%D0%B1%D0%BE%D0%B9%20%D0%BA%D0%BE%D0%B4%20%D1%80%D0%B0%D0%BD%D0%BE%20%D0%B8%D0%BB%D0%B8%20%D0%BF%D0%BE%D0%B7%D0%B4%D0%BD%D0%BE,%D0%BE%D0%BD%D0%BE%20%D0%B1%D1%8B%D0%BB%D0%BE%20%D0%B4%D0%BE%20%D1%82%D0%B2%D0%BE%D0%B5%D0%B3%D0%BE%20%D0%BF%D1%80%D0%B8%D1%85%D0%BE%D0%B4%D0%B0%C2%BB.&text=%D0%9F%D0%BE%D1%82%D0%BE%D0%BC%D1%83%20%D1%87%D1%82%D0%BE%20%D0%BF%D0%BE%20%D1%81%D1%82%D0%B0%D1%82%D0%B8%D1%81%D1%82%D0%B8%D0%BA%D0%B5%20%D1%81%D0%BE%D0%BE%D1%82%D0%BD%D0%BE%D1%88%D0%B5%D0%BD%D0%B8%D0%B5,%D0%BA%D0%BE%D0%B4%D0%B0%20%D0%BD%D1%83%D0%B6%D0%BD%D0%BE%20%D0%BF%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%BD%D0%BE%20%D1%87%D0%B8%D1%82%D0%B0%D1%82%D1%8C%20%D1%81%D1%82%D0%B0%D1%80%D1%8B%D0%B9.

2020-11-19 14:13 UTC, dlohvinov commented on src/store/modules/permissions/objects/objects.js
> +                console.log(`Cound not identify access mode '${want}'`);
хотілося б не консоль лог, а `new Error('error message')`

2020-11-19 14:13 UTC, dlohvinov commented on src/store/modules/permissions/objects/objects.js
> +            default:
щось тут якась муть, так і хочеться щось з нею зробити, але я не пам'ятаю логіки з тими цифрами :(

2020-11-19 14:13 UTC, dlohvinov commented on src/store/modules/permissions/objects/objects.js
> +        await context.commit('TOGGLE_DEFAULT_MODE', {mode, ruleName, index});
`commit()` завжди синхронний, його чекати не треба :)

2020-11-19 14:13 UTC, dlohvinov commented on src/store/modules/permissions/objects/objects.js
> +            await patchObjectDefaultPermissions(state.itemId, grantor.id, item);
мені здається використання слова Дефолт там, де щось конфігається, мутним, але, я не розумію який тут бізнес кейс, тому сподіваюсь, ти мені поясниш. чому тут то так :(

2020-11-19 14:13 UTC, dlohvinov commented on src/components/permissions/objects/opened-object-permissions-role-defaults-popup.vue
> +                } catch {}
якщо тут не перехопити і не викинути помилку 
```catch(err) { throw err; }``` 
то, якщо вона станеться, ти цього не побачиш у консолі

2020-11-19 14:16 UTC, VoroniakPavlo commented on src/components/contact-center/queues/offline-queue/opened-queue-offline-queue-general.vue
> +                    return this.$store.state.ccenter.queues.itemInstance.payload.recordings || false;
це для старих записів, для нових завжди буде фолс

2020-11-19 14:17 UTC, VoroniakPavlo commented on src/components/contact-center/queues/outbound-ivr-queue/opened-queue-outbound-ivr-general.vue
> +                    return this.$store.state.ccenter.queues.itemInstance.payload.recordings || false;
+

2020-11-19 14:17 UTC, VoroniakPavlo commented on src/components/contact-center/queues/predictive-dialer/opened-queue-predictive-dialer-general.vue
> +                    return this.$store.state.ccenter.queues.itemInstance.payload.recordings || false;
+

2020-11-19 14:17 UTC, VoroniakPavlo commented on src/locale/ru/ru.js
> +                recordings: "Recording",
зараз взнаю переклад

2020-11-19 14:18 UTC, VoroniakPavlo commented on src/locale/en/en.js
> +                recordings: "Recording",
в структурі поле в множині, але по логіці то булеве поле чи записувати розмову, походу так

2020-11-19 14:19 UTC, VoroniakPavlo commented on src/components/contact-center/queues/offline-queue/opened-queue-offline-queue-general.vue
> +                setPayloadItemProp: 'SET_PAYLOAD_ITEM_PROPERTY',
ок

2020-11-19 14:22 UTC, dlohvinov commented on src/locale/en/en.js
> +                recordings: "Recording",
оки, добре

2020-11-19 14:23 UTC, dlohvinov commented on src/components/contact-center/queues/offline-queue/opened-queue-offline-queue-general.vue
> +                setPayloadItemProp: 'SET_PAYLOAD_ITEM_PROPERTY',
сенку)

2020-11-19 14:26 UTC, dlohvinov commented on src/store/modules/permissions/objects/objects.js
> +            default:
якщо це треба вже на сьогодні, то можна скіпнути, я думаю

2020-11-20 14:10 UTC, dlohvinov commented on src/components/permissions/objects/opened-object-permissions-role-defaults-popup.vue
> +                } catch(error) { throw err; }
err is undefined :)

2020-11-20 14:10 UTC, dlohvinov commented on src/store/modules/permissions/objects/objects.js
> +        } catch {} finally {
finally на наступний рядок, будь ласка:

catch {
} finally {
} 

десь так)

2020-11-20 14:10 UTC, dlohvinov commented on src/store/modules/permissions/objects/objects.js
> +        if(ruleName == 'r' || ruleName == 'w' || ruleName == 'd') { have = rule.perm[ruleName];}
:+1:

2020-11-20 14:10 UTC, dlohvinov commented on src/store/modules/permissions/objects/objects.js
> +        if(ruleName == 'r' || ruleName == 'w' || ruleName == 'd') { have = rule.perm[ruleName];}
можна ще `{}` після `if` у одну стрічку забрати, і буде пісня))

2020-11-23 14:03 UTC, merged