Auto stash before merge of "develop" and "origin/develop"
webitel/client pull request #79
Opened 2021-01-14 11:50 UTC by VoroniakPavlo

refactor: refactored permissions page and tabs

2021-01-14 14:30 UTC, dlohvinov requested changes

2021-01-14 14:30 UTC, dlohvinov commented on src/api/utils/ApiControllers/Permissions/WebitelAPIPermissionsGetter.js
> +                            },
поясни будь ласка, що тут відбувається (або якийсь референс на апі доку), бо зовсім незроуміло чому так і для чого і при якій зміні воно може відвалитись :/

2021-01-14 14:30 UTC, dlohvinov commented on src/api/utils/ApiControllers/Permissions/WebitelAPIPermissionsGetter.js
> +            return { list: formattedResponse, next: response.next};
писав вище

2021-01-14 14:30 UTC, dlohvinov commented on src/components/permissions/objects/opened-object-permissions-defaults.vue
> +
видалити

2021-01-14 14:30 UTC, dlohvinov commented on src/components/permissions/objects/opened-object-permissions-defaults.vue
> +    <header ref="rbac" class="content-header">
для чого тут `ref="rbac"`?

2021-01-14 14:30 UTC, dlohvinov commented on src/components/permissions/objects/opened-object-permissions-defaults.vue
> +          <div>
тут би перевірити на `<div>` чи є грантор, щоб не поламати юайку, якщо щось крешнеться: `v-if="item.grantor"`

2021-01-14 14:30 UTC, dlohvinov commented on src/components/permissions/objects/opened-object-permissions-defaults.vue
> +          <div>
те саме

2021-01-14 14:30 UTC, dlohvinov commented on src/components/permissions/objects/opened-object-permissions-defaults.vue
> +            allow-empty: false
воно якось таки допомагає?))

2021-01-14 14:30 UTC, dlohvinov commented on src/components/permissions/objects/opened-object-permissions-defaults.vue
> +                item: item,
`item: item` -> `item`

2021-01-14 14:30 UTC, dlohvinov commented on src/components/permissions/objects/opened-object-permissions-defaults.vue
> +            allow-empty: false
на наступному селекті його вже немає -- схоже, не сильно))

2021-01-14 14:30 UTC, dlohvinov commented on src/components/permissions/objects/opened-object-permissions-defaults.vue
> +                item: item,
вище писав

2021-01-14 14:30 UTC, dlohvinov commented on src/components/permissions/objects/opened-object-permissions-defaults.vue
> +import editComponentMixin from "@/mixins/editComponentMixin";
`@` -> `../../../`

2021-01-14 14:30 UTC, dlohvinov commented on src/components/permissions/objects/opened-object-permissions-defaults.vue
> +import { mapActions, mapState } from "vuex";
лінтер мав би гавкати, що імпорти з ліб (абсолютний шлях) мають бути вище за імпорти з проекту (відносний шлях)

2021-01-14 14:30 UTC, dlohvinov commented on src/components/permissions/objects/opened-object-permissions-defaults.vue
> +import rolePopup from "./opened-object-permissions-role-defaults-popup";
також лінтер мав би гавкнути на `""` замість `''`, назви імпортованих компонентів мають бути у `PascalCase` і на компоненти у імпорт дописувати розширення файлу `.vue`  -- тут прям фіксати певне вже впадлу буде, але на майбутнє врахуй це будь ласка -- не хочеться про це кожен раз замість лінтера писати))

2021-01-14 14:30 UTC, dlohvinov commented on src/components/permissions/objects/opened-object-permissions-defaults.vue
> +import rolePopup from "./opened-object-permissions-role-defaults-popup";
тобто,
`import rolePopup from "./opened-object-permissions-role-defaults-popup";` 
-> 
`import RolePopup from './opened-object-permissions-role-defaults-popup.vue';`

2021-01-14 14:30 UTC, dlohvinov commented on src/components/permissions/objects/opened-object-permissions-defaults.vue
> +          id: 1,
і от тут ту енамку з дозволами було б круто якось заюзати

2021-01-14 14:30 UTC, dlohvinov commented on src/components/permissions/objects/opened-object-permissions-defaults.vue
> +      headerTitle: "", // header title. retieves from object GET request
може я десь пропустив: я не знайшов, де це використовується?

2021-01-14 14:30 UTC, dlohvinov commented on src/components/permissions/objects/opened-object-permissions-general.vue
> +  <section>
у цьому компоненті ті самі зауваження, що і вище

2021-01-14 14:30 UTC, dlohvinov commented on src/components/permissions/objects/opened-object-permissions-general.vue
> +  },
ти у попередньому компоненті це зробив через мапСтейт, а тут от так
перероби будь ласка, як у попередньому (врахуй, що тобі і сетати значення треба буде через фукнцію, а не `v-model` на проперті

2021-01-14 14:30 UTC, dlohvinov commented on src/store/modules/permissions/objects/objects.js
> +            size: '10',
сайз намбер мб?

2021-01-14 14:30 UTC, dlohvinov commented on src/store/modules/permissions/objects/objects.js
> +        const response = await getObjectList(state.itemSearch, state.itemPage, state.itemSize);
`state.///` -> `context.state.///`

2021-01-14 14:30 UTC, dlohvinov commented on src/store/modules/permissions/objects/objects.js
> +        },
поясни будь ласка, чому так?

2021-01-14 14:30 UTC, dlohvinov commented on src/store/modules/permissions/objects/objects.js
> +        let changes = prop == 'obac' ? {obac: value} : {rbac: value}
про ` ` у `{ }` вище писав

2021-01-14 14:30 UTC, dlohvinov commented on src/store/modules/permissions/objects/objects.js
> +            const response = await getObjectPermissions(state.itemId, state.operationInstance.page, state.operationInstance.size, state.operationInstance.search);
`state` -> `context.state`

2021-01-14 14:30 UTC, dlohvinov commented on src/store/modules/permissions/objects/objects.js
> +                debugger
delet

2021-01-14 14:30 UTC, dlohvinov commented on src/store/modules/permissions/objects/objects.js
> +        if(ruleName == 'c' || ruleName == 'r' || ruleName == 'w' || ruleName == 'd') { have = rule.access[ruleName];}
у `if` в одну стрічку не треба `{}`

2021-01-14 14:30 UTC, dlohvinov commented on src/store/modules/permissions/objects/objects.js
> +            const rbac = await fetchObjclassDefaultList(state.itemId, state.recordsInstance.page, state.recordsInstance.size, state.recordsInstance.search);
вище писав

2021-01-14 14:30 UTC, dlohvinov commented on src/store/modules/permissions/objects/objects.js
> +    TOGGLE_DEFAULT_MODE: async (context, {mode, ruleName, item}) => {
про пробіли вище писав

2021-01-14 14:30 UTC, dlohvinov commented on src/store/modules/permissions/objects/objects.js
> +        operationInstance: {
я продивився весь файлик: схоже, ти хотів запхати логіку 2х таб у один стор, так?
може, у такому разі, їх було би доречно на 2 розділити, щоб не розтянувати 1 файл мільйоном сторінок з довгими специфічними назвами?

2021-01-15 15:46 UTC, VoroniakPavlo commented on src/api/permissions/objects/objects.js
> +            next: response.next
я сергію напишу, нехай добавить пагінацію

2021-01-15 15:48 UTC, VoroniakPavlo commented on src/api/permissions/objects/objects.js
> +export const fetchObjclassDefaultList = async (oid, page, size, search) => {
objectId

2021-01-15 16:07 UTC, VoroniakPavlo commented on src/api/utils/ApiControllers/Permissions/WebitelAPIPermissionsGetter.js
> +                            },
тут переводжу зі строки вигляду "xrwdxrwd" в обєкт який зрозумілий для селекту

2021-01-15 16:08 UTC, VoroniakPavlo commented on src/components/permissions/objects/opened-object-permissions-defaults.vue
> +    <header ref="rbac" class="content-header">
просто тестив і не забрав

2021-01-15 16:09 UTC, VoroniakPavlo commented on src/components/permissions/objects/opened-object-permissions-defaults.vue
> +            allow-empty: false
ні, забув забрати

2021-01-16 12:14 UTC, VoroniakPavlo commented on src/store/modules/permissions/objects/objects.js
> +        },
чомусь подумав шо через нестед буде погано, і зробив так
там посуті 2 таблиці всередині і все, полів нема, там навіть кнопку сейв забрав

2021-01-16 12:17 UTC, VoroniakPavlo commented on src/store/modules/permissions/objects/objects.js
> +        operationInstance: {
наступним пр зроблю, зараз вже хочуть тестити, я зараз переробляю пермішини у всіх розділах, тому зразу і перероблю стор для розділу пермішини

2021-01-27 11:01 UTC, merged